import {useState} from 'react';import {useQuery} from '@tanstack/react-query';import {request} from '../../shared/api/client';import {collection} from '../../shared/utils/contracts.mjs';import {label} from '../../shared/utils/labels';
const refs:Record<string,[string,string,string]>={greenhouseCode:['Farm/GetByFilter','name','name'],provinceCode:['location/Provinces','name','name'],countyCode:['location/Counties','name','name'],userCode:['User/GetUserByFilter','userName','userName'],expertCode:['User/GetUserByFilter','userName','userName'],providerCode:['User/GetUserByFilter','userName','userName'],receiverCode:['User/GetUserByFilter','userName','userName'],senderCode:['User/GetUserByFilter','userName','userName'],authorCode:['User/GetUserByFilter','userName','userName'],farmCode:['Farm/GetByFilter','name','name'],productCode:['Product/GetByFilter','name','name'],agriculturalProductCode:['AgriculturalProduct/GetByFilter','name','name'],categoryCode:['Category/GetByFilter','name','name'],parentCategoryCode:['Category/GetByFilter','name','name'],warehouseCode:['Warehouse/GetByFilter','name','name']};
export function isReference(key:string){return !!refs[key];}
export default function ReferencePicker({name,value,onChange,required}:{name:string;value:string;onChange:(v:string)=>void;required:boolean}){
 const [term,setTerm]=useState('');const [search,setSearch]=useState<string|null>(null);const [path,filter,title]=refs[name];
 const query=useQuery({queryKey:['reference',path,search],queryFn:()=>request('/'+path,'GET',undefined,{[filter]:search,pageSize:50,pageNumber:1}),enabled:search!==null,retry:false});
 const rows=collection(query.data).items;
 return <div className="reference"><input aria-label={label(name)} value={value||''} onChange={e=>onChange(e.target.value)} required={required} placeholder="کد رکورد" dir="ltr"/><div className="reference-search"><input aria-label={'جست‌وجوی '+label(name)} value={term} onChange={e=>setTerm(e.target.value)} placeholder="جست‌وجو با نام"/><button type="button" onClick={()=>setSearch(term)}>جست‌وجو</button></div>{query.isFetching&&<small>در حال دریافت…</small>}{query.error&&<small className="text-red-700">{query.error.message}</small>}{search!==null&&!query.isFetching&&<select aria-label="انتخاب نتیجه" value="" onChange={e=>{onChange(e.target.value);setSearch(null);}}><option value="">{rows.length?'انتخاب از نتایج':'نتیجه‌ای پیدا نشد'}</option>{rows.map((r:any)=><option key={r.code} value={r.code}>{r[title]||r.fName||r.code} {r.lName||''} — {r.code}</option>)}</select>}</div>;
}
