// Run after npm run dev. Optional: npm install --no-save playwright && npx playwright install chromium.
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const catalog=JSON.parse(fs.readFileSync(path.join(__dirname,'../src/shared/api/catalog.json'),'utf8'));
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:5174';const shots=process.env.TEST_SCREENSHOTS;
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.TEST_CHROMIUM_PATH?{executablePath:process.env.TEST_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--disable-webgl']}: {})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();const pageErrors=[];page.on('pageerror',e=>pageErrors.push(e.message));
 let role='Admin',moderations=[],mutations=[],failNext=false,expired=false,refreshes=0;
 const common={code:'TEST000001',name:'محصول نمونه',title:'عنوان نمونه',content:'کیفیت محصول خوب بود؛ بسته‌بندی هم مناسب بود.',statusCode:'PENDING001',createdAt:'2026-10-07T10:00:00Z',fName:'مسعود',lName:'آزمایشی',phoneNumber:'09120000000',roleName:'Buyer',retailPrice:240000,wholesalePrice:210000,stock:25,categoryCodes:['CATEGORY01'],farmName:'گلخانه نمونه',greenhouseCode:'FARM000001',qualityGrade:'PENDING',allowedActions:['Approve','Reject'],paymentStatus:'Held',totalPrice:2400000,discountAmount:0,price:240000,numberOfVases:3,serviceType:'HomePlantCare',description:'رسیدگی به گیاهان',providerCode:null,addressCode:'ADDRESS001',address:{code:'ADDRESS001',street:'خیابان نمونه',postalCode:'1234567890',provinceCode:'PROVINCE01',countyCode:'COUNTY0001',isDefault:false},rating:5,providerCode:null};
 await context.route('**/api/**',async route=>{const req=route.request();const url=new URL(req.url());if(!url.pathname.startsWith('/api/'))return route.continue();const p=url.pathname.replace('/api','');const method=req.method();const data=(req.headers()['content-type']||'').includes('application/json')?req.postDataJSON():null;const send=(value,status=200)=>route.fulfill({status,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'},body:JSON.stringify(value)});const ok=d=>send({IsSuccess:true,Data:d});if(method==='OPTIONS')return send({});
  if(p==='/Auth/GuestToken')return ok({Token:'Bearer guest'});
  if(p==='/Auth/Login')return ok({Token:'Bearer access',RefreshToken:'refresh'});
  if(p==='/Auth/RefreshToken'){refreshes++;expired=false;return ok({Token:'Bearer renewed',RefreshToken:'refresh2'});}
  if(expired)return send({message:'expired'},401);
  if(p==='/User/GetRole')return ok({RoleName:role,RoleNames:[role]});
  if(p==='/User/GetMyProfile')return ok({User:{Code:'ADMIN00001',FName:'مسعود',UserName:'admin'}});
  if(p==='/Admin/Lookups')return ok({Statuses:[{Code:'PENDING001',Name:'در انتظار تأیید',StatusId:81,EntityStatus:'CommentStatus'},{Code:'APPROVE001',Name:'تأییدشده',StatusId:82,EntityStatus:'CommentStatus'},{Code:'REJECT0001',Name:'ردشده',StatusId:83,EntityStatus:'CommentStatus'},{Code:'SERVICE001',Name:'ثبت‌شده',EntityStatus:'ServiceRequestStatus'},{Code:'CATEGORY01',Name:'فعال',EntityStatus:'Category'}],Roles:[{Code:'ROLEADMIN1',Name:'Admin'},{Code:'ROLEEXPERT',Name:'Expert'},{Code:'ROLEBUYER1',Name:'Buyer'}],FileTypes:[{Code:'IMAGE00001',Name:'تصویر'}]});
  if(p==='/Admin/Dashboard')return ok({PendingComments:7,UnassignedServices:3,PendingQuality:4,Orders:52,Users:128,Farms:12,Products:180,UpdatedAt:'2026-10-07T10:00:00Z'});
  if(p.includes('/Moderate')){moderations.push(data);return ok({Code:'TEST000001',StatusCode:'APPROVE001'});}
  if(p.includes('/Roles')&&method==='GET')return ok({RoleCodes:['ROLEEXPERT']});
  if(method!=='GET'){mutations.push({p,method,data,raw:req.postData()});if(failNext){failNext=false;return send({IsSuccess:true,Data:false});}return ok(true);}
  if(p.includes('GetByCode')||p.includes('GetUserByCode'))return ok(common);
  if(p==='/Admin/Audit')return ok({Items:[{code:'AUDIT00001',entityStatus:'CommentStatus',oldStatusCode:'PENDING001',newStatusCode:'APPROVE001',comments:'بررسی شد',changeDate:'2026-10-07T10:00:00Z'}],TotalCount:1,PageNumber:1});
  if(p.includes('/File/GetFiles'))return ok({Files:[{FileCode:'FILE000001',Url:'/uploads/test.png',EntityFile:'Article',EntityCode:'ARTICLE001'}],TotalCount:1,PageNumber:1});
  if(p.includes('/Checkout/'))return ok({Code:'CHECKOUT01',Orders:[common],PaymentStatus:'Held'});
  return ok({Items:[common],TotalCount:1,PageNumber:Number(url.searchParams.get('pageNumber')||1)});
 });
 await page.goto(base);await page.getByLabel('نام کاربری',{exact:true}).fill('admin');await page.getByLabel('رمز عبور',{exact:true}).fill('password');await page.getByRole('button',{name:'ورود به پنل',exact:true}).click();await page.getByRole('heading',{name:'سلام مسعود، خوش آمدید.'}).waitFor();
 if(shots){fs.mkdirSync(shots,{recursive:true});await page.screenshot({path:path.join(shots,'dashboard-desktop.png'),fullPage:true});}
 console.log('PASS authenticated admin login and dashboard');
 await page.goto(base+'/#/manage/Comment');await page.getByRole('heading',{name:'نظرات کاربران',exact:true}).waitFor();await page.getByTitle('تأیید نظر',{exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'تأیید نظر',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(moderations[0].decision,'Approve');assert.equal(moderations[0].expectedStatusCode,'PENDING001');assert.equal(moderations[0].content,undefined);
 await page.getByTitle('رد نظر',{exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'رد نظر',exact:true}).click();assert.equal(moderations.length,1);await page.getByLabel('دلیل تصمیم (الزامی)',{exact:true}).fill('توهین به کاربر');await page.getByRole('dialog').getByRole('button',{name:'رد نظر',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(moderations[1].reason,'توهین به کاربر');console.log('PASS comment moderation preserves content and requires rejection reason');
 await page.goto(base+'/#/manage/ServiceRequest');await page.getByRole('button',{name:'ویرایش',exact:true}).click();const serviceDialog=page.getByRole('dialog');assert.equal(await serviceDialog.getByLabel('قیمت',{exact:true}).count(),0);await serviceDialog.getByLabel('توضیحات',{exact:true}).fill('رسیدگی انجام شود');await serviceDialog.getByRole('checkbox').check();await serviceDialog.getByRole('button',{name:'ثبت عملیات',exact:true}).click();await serviceDialog.waitFor({state:'hidden'});const update=mutations.find(m=>m.p==='/ServiceRequest/Update');assert.deepEqual(update.data,{code:'TEST000001',description:'رسیدگی انجام شود'});console.log('PASS service update sends only changed allowed fields');
 await page.goto(base+'/#/manage/Category');await page.getByRole('button',{name:'ویرایش',exact:true}).click();await page.getByRole('dialog').getByLabel('دسته‌بندی',{exact:true}).fill('TEST000001').catch(()=>{});const cat=page.getByRole('dialog');await cat.locator('input#name').fill('دسته جدید');await cat.getByRole('checkbox').check();failNext=true;await cat.getByRole('button',{name:'ثبت عملیات',exact:true}).click();await cat.getByText('سرور انجام عملیات را تأیید نکرد.',{exact:true}).waitFor();assert.equal(await cat.isVisible(),true);assert.equal(mutations.at(-1).data.categoryCode,'TEST000001');await cat.getByRole('button',{name:'انصراف',exact:true}).click();console.log('PASS update identifier mapping and false response stay visible');
 await page.goto(base+'/#/manage/AgriculturalOrder');await page.getByRole('button',{name:'عملیات سفارش',exact:true}).click();const order=page.getByRole('dialog');assert.equal(await order.locator('select#action option[value="Ship"]').count(),0);await order.locator('select#action').selectOption('Reject');assert.equal(await order.locator('#reason').getAttribute('required'),'');await order.getByRole('button',{name:'انصراف',exact:true}).click();console.log('PASS order actions follow backend allowedActions');
 await page.goto(base+'/#/manage/User');await page.getByRole('button',{name:'مدیریت نقش‌ها',exact:true}).click();await page.getByRole('dialog').getByRole('checkbox',{name:'کارشناس',exact:true}).waitFor();assert.equal(await page.getByRole('dialog').getByRole('checkbox',{name:'کارشناس',exact:true}).isChecked(),true);await page.getByRole('dialog').getByRole('button',{name:'انصراف',exact:true}).click();console.log('PASS role editor loads existing assignments');
 await page.goto(base+'/#/manage/Article');await page.getByLabel('کد برای مشاهده مستقیم',{exact:true}).fill('ARTICLE001');await page.getByRole('button',{name:'دریافت با کد',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'ویرایش',exact:true}).click();await page.getByRole('dialog').locator('input#articleCode').fill('TEST000001');await page.getByRole('dialog').getByRole('button',{name:'انصراف',exact:true}).click();console.log('PASS direct record lookup and actions from detail');
 await page.goto(base+'/#/manage/Farm');await page.getByRole('button',{name:'ثبت جدید',exact:true}).click();const farm=page.getByRole('dialog');await farm.locator('input#name').fill('گلخانه تست');await farm.locator('input#minPurchase').fill('0');await farm.getByRole('button',{name:'افزودن اطلاعات',exact:true}).click();await farm.locator('input#street').fill('خیابان نمونه');await farm.locator('input#postalCode').fill('1234567890');await farm.getByLabel('استان',{exact:true}).fill('PROVINCE01');await farm.getByLabel('شهرستان',{exact:true}).fill('COUNTY0001');await farm.locator('input[type=file]').setInputFiles({name:'farm.png',mimeType:'image/png',buffer:Buffer.from('test image')});await farm.getByRole('checkbox').check();await farm.getByRole('button',{name:'ثبت عملیات',exact:true}).click();await farm.waitFor({state:'hidden'});const farmUpload=mutations.find(m=>m.p==='/Farm/Create');assert.ok(farmUpload.raw.includes('name="address.street"'));assert.ok(farmUpload.raw.includes('filename="farm.png"'));assert.ok(!farmUpload.raw.includes('[object Object]'));console.log('PASS real multipart upload includes nested address and image');
 
 const modules=['Comment','ServiceRequest','QualityAssessment','AgriculturalOrder','User','Farm','AgriculturalProduct','Product','Category','Auction','AuctionBid','Discount','Warehouse','WarehouseInventory','Order','Article','Slider','ChatMessage','File','Notification','StatusChangeLog','Location'];
 for(const module of modules){await page.goto(base+'/#/manage/'+module);await page.locator('h1').waitFor();await page.locator('tbody tr').first().waitFor();}
 console.log('PASS all 22 resource screens render');
 expired=true;await page.goto(base+'/#/');await page.getByRole('button',{name:'به‌روزرسانی',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.stat-card strong')?.textContent!=='…');assert.equal(refreshes,1);console.log('PASS expired session refresh');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'/#/');await page.reload();await page.getByRole('heading',{name:'سلام مسعود، خوش آمدید.'}).waitFor();await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().left>=window.innerWidth-1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);if(shots)await page.screenshot({path:path.join(shots,'dashboard-mobile.png'),fullPage:true,animations:'disabled'});await page.getByLabel('بازکردن منو',{exact:true}).click();await page.locator('.sidebar').getByRole('link',{name:'نظرات کاربران',exact:true}).click();await page.getByTitle('رد نظر',{exact:true}).click();if(shots)await page.screenshot({path:path.join(shots,'comment-mobile.png'),fullPage:true,animations:'disabled'});await page.getByRole('dialog').getByLabel('بستن',{exact:true}).click();console.log('PASS mobile navigation and dialog layout');
 await page.getByLabel('خروج از حساب',{exact:true}).click();await page.getByLabel('نام کاربری',{exact:true}).waitFor();role='Buyer';await page.getByLabel('نام کاربری',{exact:true}).fill('buyer');await page.getByLabel('رمز عبور',{exact:true}).fill('password');await page.getByRole('button',{name:'ورود به پنل',exact:true}).click();await page.getByText('این حساب دسترسی مدیریت ندارد.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>sessionStorage.getItem('ag-admin-token')),null);console.log('PASS non-admin denied and credentials cleared');
 assert.deepEqual(pageErrors,[]);console.log('PASS no uncaught browser errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
